sb:
  config:
    robot:
      - name: '机器人'
        qq: 123456


#################### 以下配置勿动 ####################
spring:
  bot:
    # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
    plugin-list:
      - cn.yiidii.sb.plugin.LtReplyPlugin
      - cn.yiidii.sb.plugin.FriendRequestEventPlugin
  application:
    name: sb
server:
  port: 8081

logging:
  config: classpath:logback-sb.xml

pigeon:
  log:
    path: logs
    level: info
  strategy:
    basePackage: cn.yiidii